### Common-Utilities Build Matrix ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode12
  - xcode10
dist: focal
arch:
  - arm64
  - amd64

notifications:
  email: false


### Standard Installation Procedure ###
script:
  - mkdir build && cd build
  - cmake ../. -Dutils_build_tests=ON
  - make && sudo make install
  - cd test
  - ctest


### Provide Code Coverage Reports ###
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      arch: amd64
      addons:
        apt:
          packages:
            - python-pip
            - lcov
          update: true
      install:
        - if [ $TRAVIS_OS_NAME = linux ]; then pip install --user cpp-coveralls; fi
      script:
        - mkdir build && cd build
        - cmake ../. -Dutils_coverage=ON
        - make && sudo make install
        - cd test
        - ctest
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '*gtest*' '*/test/*' '/usr/*' --output-file coverage.info
        - coveralls -r ../../. --l coverage.info -n
