### Continuous Integration for Utilities-API ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode11.2
  - xcode10.1
dist: bionic
arch:
  - arm64
  - amd64

notifications:
  email: false


### Installation procedure ###
addons:
  homebrew:
    packages:
      - pyenv
    update: true

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build && cd build

script:
  - cmake ../. -Dcoverage=1 -Dbuild_all_tests=ON
  - make && sudo make install
  - cd test
  - ctest

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
