###  Utilities-API Build Matrix ###
language: cpp
os:
  - linux
  # - osx
compiler:
#  - clang
  - gcc
# osx_image:
#   - xcode11.2
#   - xcode10.1
dist: bionic
arch:
  - arm64
  - amd64

notifications:
  email: false

addons:
  apt:
    packages:
      - python-pip
      - lcov


### Installation procedure ###
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get upgrade gcov pip install --user cpp-coveralls; fi
script:
  - mkdir build && cd build
  - cmake ../. -Dutils-api_coverage=ON
  - make && sudo make install
  - cd test
  - ctest
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '*gtest*' '*/test/*' '/usr/*' --output-file coverage.info
  - coveralls -r ../../. --l coverage.info -n
