### Continuous Integration for Utilities-API ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode11.2
  - xcode10.1
dist: bionic
arch:
  - arm64
  - amd64

notifications:
  email: false


### Installation procedure ###
script:
  - mkdir build && cd build
  - cmake ../. -Dutils-api_build_tests=ON
  - make && sudo make install
  - cd test
  - ctest
