### Common-Utilities Build Matrix ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode12
  - xcode10
dist: focal
arch:
  - arm64
  - amd64

notifications:
  email: false


### Standard Installation Procedure ###
script:
  - mkdir build-tests && cd build-tests
  - cmake ../. -Dutils_build_tests=ON
  - make && sudo make install
  - ctest --output-on-failure
  - cd ../
  - mkdir build-samples && cd build-samples
  - cmake ../. -Dutils_build_samples=ON
  - make
  - cd bin/samples
  - for file in *; do ./$file || echo -n; done


### Provide Code Coverage Reports ###
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      arch: amd64
      addons:
        apt:
          packages:
            - python-pip
            - lcov
          update: true
      install:
        - if [ $TRAVIS_OS_NAME = linux ]; then pip install --user cpp-coveralls; fi
      script:
        - mkdir build && cd build
        - cmake ../. -Dutils_coverage=ON
        - make && sudo make install
        - ctest --output-on-failure
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '*gtest*' '*/tests/*' '/usr/*' --output-file coverage.info
        - coveralls -r ../../. --l coverage.info -n
        - bash <(curl -s https://codecov.io/bash)
